### ISSUE TITLE
Implement imports

### ISSUE THREAD

**Issue by niedbalski** [niedbalski/repeat#1]
Repeat should support importing raw files from file:/// and http:///. As an example:

```yaml
import:
  - https://github.com/niedbalski/repeat/raw/socktstat.yaml
  - https://github.com/niedbalski/repeat/raw/meminfo.yaml
  - file://./extra_checks.yaml

collections:
  process_list:
       .....
```

This definition will fetch and merge the collections defined in the imported
yaml(s) files. Circular recursion will be validated by indexing by each collection name.

Also, each import might have a #md5sum property, that will be validated upon
checkout.
