### ISSUE TITLE
Implement database output

### ISSUE THREAD

**Issue by niedbalski** [niedbalski/repeat#2]
Repeat should support storing each collection output into a 
database table that can be later queried by a jupyter notebook or a python 
dataframe extension.

```yaml
collections:
  process_list:
[...]
    store: database
    database:
      map-values:
        separator: " "
        fields:
          - name: value
            type: string
            idx: 0
```
For achieving this, the configuration file should be extended for each collection to be
able to decide which storage backend should be in use (database, file)

If database is selected, a map-values section should be defined, this section
should have the following fields (primarly identified ones)

* separator: which character separates each field in the output.
* type: the type of the field
* idx: the index (from 0 index) in the command output after splitting by the separator
* name: the name of the field in the database

As an example:

```yaml
collections:

  process_list:
    command: ps auxh
    run-every: 2s
    exit-codes: any
    store: database
    database:
      map-values:
        separator: " "
        fields:
          - name: value
            type: string
            idx: 0
```
